export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 5,
  MAX_PAGE_SIZE: 100,
  MIN_PAGE_SIZE: 1,
};

export enum NodeType {
  INITIAL = "INITIAL",
  MANUAL_TRIGGER = "MANUAL_TRIGGER",
  HTTP_REQUEST = "HTTP_REQUEST",
  GOOGLE_FORM_TRIGGER = "GOOGLE_FORM_TRIGGER",
  STRIPE_TRIGGER = "STRIPE_TRIGGER",
  ANTHROPIC = "ANTHROPIC",
  GEMINI = "GEMINI",
  OPENAI = "OPENAI",
  DISCORD = "DISCORD",
  SLACK = "SLACK",
}

export enum ExecutionStatus {
  RUNNING = "RUNNING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
}
